-- Markdown preview plugin disabled due to errors
-- return {
--   {
--     "iamcco/markdown-preview.nvim",
--     cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
--     build = function()
--       vim.fn["mkdp#util#install"]()
--     end,
--     ft = { "markdown" },
--     config = function()
--       -- Set some useful options
--       vim.g.mkdp_auto_start = 0  -- Don't auto-start preview
--       vim.g.mkdp_auto_close = 1  -- Auto-close preview when leaving markdown buffer
--       vim.g.mkdp_refresh_slow = 0  -- Fast refresh
--       vim.g.mkdp_command_for_global = 0  -- Only enable for markdown files
--       vim.g.mkdp_open_to_the_world = 0  -- Don't allow external access
--       vim.g.mkdp_open_ip = "127.0.0.1"  -- Localhost only
--       vim.g.mkdp_port = "8080"  -- Default port
--       vim.g.mkdp_browser = ""  -- Use system default browser
--       vim.g.mkdp_filetypes = { "markdown" }
--
--       -- Keymaps for markdown preview
--       vim.keymap.set("n", "<leader>mp", "<cmd>MarkdownPreviewToggle<cr>", { desc = "Toggle Markdown Preview" })
--     end,
--   },
-- }

-- Return empty table to disable all markdown plugins
return {}